package com.apoorvdarshan.calorietracker.ui.workouts

import java.util.Locale

/** Display-only translations: persisted names, IDs, filter keys and numeric inputs stay intact. */
internal object WorkoutStrings {
    private val chinese = mapOf(
        "calculate" to "计算",
        "calculating…" to "计算中…",
        "calorie burn" to "热量消耗",
        "calculate calorie burn" to "计算热量消耗",
        "calculating calorie burn" to "正在计算热量消耗",
        "sets" to "组数",
        "workouts" to "训练动作",
        "reps" to "次数",
        "burn" to "消耗",
        "today" to "今天",
        "tomorrow" to "明天",
        "yesterday" to "昨天",
        "selected day" to "所选日期",
        "no workouts logged" to "还没有训练记录",
        "add workout" to "添加训练",
        "all exercises" to "全部动作",
        "copy from day" to "从其他日期复制",
        "saved" to "已收藏",
        "saved exercises" to "收藏的动作",
        "create exercise" to "创建动作",
        "add exercise" to "添加动作",
        "add to day" to "添加到当天",
        "remove from day" to "从当天移除",
        "edit exercise" to "编辑动作",
        "edit" to "编辑",
        "save" to "保存",
        "unsave" to "取消收藏",
        "delete" to "删除",
        "delete exercise" to "删除动作",
        "save exercise" to "收藏动作",
        "unsave exercise" to "取消收藏动作",
        "remove exercise" to "移除动作",
        "done" to "完成",
        "cancel" to "取消",
        "ok" to "知道了",
        "log your workout first" to "请先记录训练",
        "stop and save an exercise timer, or enter reps for at least one set, before calculating workout calories." to "请先停止并保存一个动作的计时，或至少填写一组训练次数，再计算热量消耗。",
        "history" to "历史记录",
        "no lift history yet" to "还没有该动作的训练记录",
        "open exercise instructions" to "查看动作说明",
        "remove set" to "减少一组",
        "add blank set" to "添加一组",
        "timed activity" to "计时训练",
        "pause" to "暂停",
        "resume" to "继续",
        "stop & save" to "停止并保存",
        "restart timer" to "重新计时",
        "discard timer" to "放弃计时",
        "restart timer?" to "重新开始计时？",
        "discard timer?" to "放弃本次计时？",
        "restart" to "重新开始",
        "discard" to "放弃",
        "running" to "计时中",
        "saved" to "已保存",
        "paused" to "已暂停",
        "primary" to "主要肌群",
        "secondary" to "辅助肌群",
        "primary muscles" to "主要肌群",
        "secondary muscles" to "辅助肌群",
        "equipment" to "器械",
        "level" to "难度",
        "force" to "发力方式",
        "mechanic" to "动作类型",
        "category" to "训练类别",
        "name" to "名称",
        "instructions" to "动作说明",
        "body part" to "身体部位",
        "what to copy" to "复制内容",
        "without details" to "仅复制动作",
        "with set details" to "包含每组详情",
        "adds exercise names only, with blank sets." to "只复制动作名称，每组数据留空。",
        "copies sets, weights, reps, rpe, units, and timers." to "复制组数、重量、次数、用力程度、单位和计时数据。",
        "close copy picker" to "关闭日期选择",
        "no earlier workout days to copy." to "没有可复制的历史训练记录。",
        "no matching exercises" to "没有符合条件的动作",
        "try clearing filters — or create your own exercise." to "试试清除筛选条件，或创建自己的动作。",
        "no saved exercises" to "还没有收藏动作",
        "bookmark exercises from the dataset to keep them here." to "在动作库中收藏动作后，就会显示在这里。",
        "dataset" to "动作库",
        "all" to "全部",
        "delete this custom exercise?" to "删除这个自定义动作？",
        "this removes the exercise from your library. logged workouts keep their history." to "将从动作库中删除该动作，已记录的训练历史会保留。",
        "add photo (optional)" to "添加照片（选填）",
        "remove photo" to "移除照片",
        "start over" to "重新填写",
        "could not prepare the workout. try again." to "未能生成训练内容，请重试。",
        "could not save the workout. try again." to "未能保存训练，请重试。",
        "show exercise library" to "打开动作库",
        "show workout log" to "打开训练记录",
        "abdominals" to "腹肌",
        "abductors" to "髋外展肌群",
        "adductors" to "髋内收肌群",
        "biceps" to "肱二头肌",
        "calves" to "小腿肌群",
        "chest" to "胸肌",
        "forearms" to "前臂肌群",
        "glutes" to "臀肌",
        "hamstrings" to "腘绳肌",
        "lats" to "背阔肌",
        "lower back" to "下背部",
        "middle back" to "中背部",
        "neck" to "颈部",
        "quadriceps" to "股四头肌",
        "shoulders" to "肩部",
        "traps" to "斜方肌",
        "triceps" to "肱三头肌",
        "back" to "背部",
        "arms" to "手臂",
        "legs" to "腿部",
        "core" to "核心肌群",
        "upper" to "上肢",
        "lower" to "下肢",
        "push" to "推类动作",
        "pull" to "拉类动作",
        "full body" to "全身",
        "push / pull / legs" to "推／拉／腿分化",
        "upper / lower" to "上下肢分化",
        "body-part split" to "按身体部位分化",
        "arnold split" to "阿诺德分化",
        "push / pull" to "推拉分化",
        "antagonist split" to "拮抗肌分化",
        "hybrid split" to "混合分化",
        "custom" to "自定义",
        "chest + back" to "胸部＋背部",
        "shoulders + arms" to "肩部＋手臂",
        "biceps + triceps" to "肱二头肌＋肱三头肌",
        "quads + hamstrings/glutes" to "股四头肌＋腘绳肌／臀肌",
        "shoulders + lats/traps" to "肩部＋背阔肌／斜方肌",
        "accessory/core" to "辅助动作／核心",
        "core/accessory" to "核心／辅助动作",
        "strength/compound" to "力量／复合动作",
        "accessory/hypertrophy" to "辅助动作／增肌",
        "beginner" to "初级",
        "intermediate" to "中级",
        "expert" to "高级",
        "advanced" to "高级",
        "strength" to "力量训练",
        "cardio" to "有氧训练",
        "stretching" to "拉伸",
        "plyometrics" to "增强式训练",
        "powerlifting" to "力量举",
        "olympic weightlifting" to "奥林匹克举重",
        "strongman" to "大力士训练",
        "compound" to "复合动作",
        "isolation" to "孤立动作",
        "static" to "静态发力",
        "barbell" to "杠铃",
        "dumbbell" to "哑铃",
        "body only" to "自重",
        "cable" to "绳索",
        "machine" to "固定器械",
        "kettlebells" to "壶铃",
        "bands" to "弹力带",
        "medicine ball" to "药球",
        "exercise ball" to "健身球",
        "foam roll" to "泡沫轴",
        "e-z curl bar" to "曲杆杠铃",
        "other" to "其他",
        "none" to "无",
        "unspecified" to "未指定",
        "database metadata" to "动作属性",
        "light" to "轻强度",
        "moderate" to "中等强度",
        "vigorous" to "高强度",
        "strength 1–10" to "力量训练 1–10",
        "cr10 0–10" to "用力程度 CR10 0–10",
        "borg 6–20" to "用力程度 Borg 6–20",
        "rpe" to "用力程度",
        "kg" to "千克",
        "lbs" to "磅",
        "kcal" to "千卡",
    )
    fun text(value: String): String {
        if (Locale.getDefault().language != "zh") return value
        chinese[value.lowercase(Locale.ROOT)]?.let { return it }
        Regex("^(\\d+) (workouts?|exercises?)$").matchEntire(value)?.let { return "${it.groupValues[1]} 个动作" }
        Regex("^(\\d+) sets?$").matchEntire(value)?.let { return "${it.groupValues[1]} 组" }
        Regex("^Set (\\d+)$").matchEntire(value)?.let { return "第 ${it.groupValues[1]} 组" }
        Regex("^All (\\d+)$").matchEntire(value)?.let { return "全部（${it.groupValues[1]}）" }
        if (value.startsWith("Last time: ")) return "上次：" + text(value.removePrefix("Last time: "))
        if (value.startsWith("Use + to pick ") && value.endsWith(" exercises for this day"))
            return "点击＋，为当天添加" + text(value.removePrefix("Use + to pick ").removeSuffix(" exercises for this day")) + "训练动作"
        if (value.startsWith("Add a previous plan to ")) return "将历史训练复制到 " + text(value.removePrefix("Add a previous plan to "))
        if (value.startsWith("This clears the recorded time for ")) return "这将清除「" + value.removePrefix("This clears the recorded time for ").removeSuffix(".") + "」的计时记录。"
        if (value.startsWith("Start timer for ")) return "开始计时：" + value.removePrefix("Start timer for ")
        if (value.startsWith("Timer options for ")) return "计时选项：" + value.removePrefix("Timer options for ").replace(Regex(", (running|saved|paused)$")) { ", " + text(it.groupValues[1]) }
        if (value.startsWith("Preview ")) return "预览：" + value.removePrefix("Preview ")
        // Joined metadata contains stable English tokens; translate only their display copy.
        for (separator in listOf(" · ", ", ", " - ")) {
            if (value.contains(separator)) return value.split(separator).joinToString(separator) { text(it) }
        }
        return value.replace(Regex("(?<=\\d) reps?\\b"), " 次")
            .replace(Regex("\\bkcal\\b"), "千卡")
            .replace(Regex("(?<=\\d) kg\\b"), " 千克")
            .replace(Regex("(?<=\\d) lbs\\b"), " 磅")
    }
}
